### ISSUE TITLE
디자인 시스템과 함수형 프로그래밍 의견 남기기

### ISSUE THREAD

**Issue by movie42** [movie42/hyunsu#3]
디자인 시스템과 함수형 프로그래밍을 읽고 남기고 싶은 의견이 있다면 댓글로 달아주세요. 자신만의 더 좋은 방법이나 더 좋은 글을 링크해주시면 감사드리겠습니다.

**Comment by saengmotmi** [comment]
마지막 예제 코드 보고 왔어요 ㅎㅎ 경우에 따라 다를 수 있겠지만 원 글에 제시된 방식보다는 버튼의 구현을 FiveBottomButtonGroup에 모두 포함시키지 않고 children으로 받도록 해서 애초에 외부로 돌리는 방법이 좋지 않을까 싶어요. 만약 하위 요소들끼리 공유해야 하는 데이터가 있다면 Context API로 공유를 하고요. https://brunch.co.kr/@finda/556 요 글에 잘 설명되어 있으니 한번 참고해보세요!

```tsx
<FiveBottomButtonGroup>
  <Button />
  <Button />
  <Button />
  <Button />
  <Button />
</FiveBottomButtonGroup>
```

**Comment by movie42** [comment]
이제 댓글이 생겼습니다. 
댓글에 남겨주세용~

**Comment by movie42** [comment]
이제 댓글이 생겼습니다.
댓글에 남겨주세용~
